# Generated by Django 5.0.5 on 2024-05-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('tokenId', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('tokenPrice', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
