# Generated by Django 5.0.5 on 2024-05-07 00:58

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Ethereum Wallet Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Ethereum Wallet Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
