# Generated by Django 5.0.5 on 2024-05-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_phone_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tokenPrice',
            new_name='productCost',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
