# Generated by Django 5.0.5 on 2024-05-12 22:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tokenprice_order_productcost_alter_order_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Ethereum Buyer Wallet Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Ethereum Seller Wallet Address'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Ethereum Wallet Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
