# Generated by Django 5.0.5 on 2024-05-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprofile_user_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
